-- DewPoint Database: Sample Data
-- Authors: Amy Ramsay, Bea Sauve
-- Date: May, 2026
-- Course: AD350 Database Technology
-- Run AFTER DewPoint_DataBase.sql
-- Samples generated by AI

USE dew_point;

-- ==========================================
-- 1. POPULATE USER TABLE (25 Rows)
-- IDs start at 10001
-- ==========================================
INSERT INTO user (first_name, last_name, email, phone_number, address) VALUES
('Amy', 'Ramsay', 'amy.ramsay@example.com', '206-555-0101', '123 Pine St, Seattle, WA 98101'),
('Bea', 'Sauve', 'bea.sauve@example.com','206-555-0102', '456 Cedar Ave, Seattle, WA 98102'),
('Bob', 'Johnson', 'bob.j@example.com', '555-0103', '789 Ocean Blvd, Miami, FL'),
('Alice', 'Williams', 'alice.w@example.com', '555-0104', '101 Puddle Ln, Austin, TX'),
('Charlie', 'Brown', 'charlie.b@example.com', '555-0105', '202 Stream Rd, Denver, CO'),
('Diana', 'Prince', 'diana.p@example.com', '555-0106', '303 River Dr, Boston, MA'),
('Evan', 'Wright', 'evan.w@example.com', '555-0107', '404 Lake Way, Chicago, IL'),
('Fiona', 'Gallagher', 'fiona.g@example.com', '555-0108', '505 Aqua Cir, Las Vegas, NV'),
('George', 'Costanza', 'george.c@example.com', '555-0109', '606 Marine Dr, New York, NY'),
('Hannah', 'Montana', 'hannah.m@example.com', '555-0110', '707 Creek Ct, Nashville, TN'),
('Ian', 'Malcolm', 'ian.m@example.com', '555-0111', '808 Geyser Pl, San Diego, CA'),
('Julia', 'Roberts', 'julia.r@example.com', '555-0112', '909 Cascade Way, Phoenix, AZ'),
('Kevin', 'Bacon', 'kevin.b@example.com', '555-0113', '111 Glacier St, Salt Lake, UT'),
('Laura', 'Croft', 'laura.c@example.com', '555-0114', '222 Fountain Ave, San Francisco, CA'),
('Michael', 'Scott', 'michael.s@example.com', '555-0115', '333 Mist Blvd, Scranton, PA'),
('Nancy', 'Drew', 'nancy.d@example.com', '555-0116', '444 Clue Ave, River Heights, IL'),
('Oscar', 'Martinez', 'oscar.m@example.com', '555-0117', '555 Accounting Way, Scranton, PA'),
('Pam', 'Beesly', 'pam.b@example.com', '555-0118', '777 Art Lane, New York, NY'),
('Quinn', 'Fabray', 'quinn.f@example.com', '555-0119', '888 Lima Rd, Lima, OH'),
('Ray', 'Romano', 'ray.r@example.com', '555-0120', '999 Queens Blvd, Queens, NY'),
('Sarah', 'Connor', 'sarah.c@example.com', '555-0121', '123 Tech Noir St, Los Angeles, CA'),
('Tom', 'Hanks', 'tom.h@example.com', '555-0122', '456 Forest Ridge, Castaway, CA'),
('Ursula', 'Buffay', 'ursula.b@example.com', '555-0123', '789 Twin Towers, New York, NY'),
('Victor', 'Frankenstein', 'victor.f@example.com', '555-0124', '101 Modern Prometheus Rd, Geneva, CH'),
('Wendy', 'Darling', 'wendy.d@example.com', '555-0125', '202 Neverland Way, London, UK');

-- ==========================================
-- 2. POPULATE SUPPLIER TABLE (15 Rows)
-- IDs start at 101
-- ==========================================
INSERT INTO supplier (name, address, phone_number, email, status, onboard, offboard) VALUES
('Alpine Springs Co', '100 Mountain Peak, Boulder, CO', '800-555-011', 'info@alpinesprings.com', 'Active', '2024-01-15', NULL),
('Pacific H2O', '200 Coastal Hwy, Eugene, OR', '800-555-022', 'sales@pach2o.com', 'Active', '2024-03-10', NULL),
('Icelandic Pure', '300 Glacier Rd, Reykjavik, IC', '800-555-033', 'import@icepure.com', 'Active', '2024-06-01', NULL),
('Desert Oasis Waters', '400 Dune Rd, Phoenix, AZ', '800-555-044', 'contact@desertoasis.com', 'Inactive', '2023-01-01', '2025-12-31'), 
('Fuji Springs', '500 Volcanic Way, Shizuoka, JP', '800-555-055', 'global@fujisprings.com', 'Active', '2025-02-18', NULL),
('Mineral Craft', '600 Limestone Ridge, Louisville, KY', '800-555-066', 'support@mincraft.com', 'Active', '2025-05-20', NULL),
('Blue Wave Bottlers', '700 Ocean Surf, San Diego, CA', '800-555-077', 'orders@bluewave.com', 'Active', '2025-08-12', NULL),
('HydroVibe Inc', '800 Tech Way, San Jose, CA', '800-555-088', 'b2b@hydrovibe.com', 'Active', '2025-11-05', NULL),
('Cascade Liquid Assets', '900 Fall Line, Portland, OR', '800-555-099', 'ops@cascadeliquid.com', 'Active', '2026-01-10', NULL),
('Zen Alkaline Waters', '150 Serenity Lane, Sedona, AZ', '800-555-100', 'om@zenalkaline.com', 'Active', '2026-02-01', NULL),
('Polar Frost', '250 Tundra Trail, Anchorage, AK', '800-555-112', 'sales@polarfrost.com', 'Active', '2026-03-15', NULL),
('Artesian Alliance', '350 Wellhead Dr, Memphis, TN', '800-555-113', 'info@artesianall.com', 'Active', '2026-04-01', NULL),
('Napa Valley Minerals', '450 Vineyard Rd, Napa, CA', '800-555-114', 'trade@napaminerals.com', 'Active', '2026-04-20', NULL),
('Old Stream Bottling', '550 Heritage Way, Roanoke, VA', '800-555-115', 'history@oldstream.com', 'Inactive', '2022-05-01', '2024-05-01'), 
('Fresh Drop Distro', '650 Raincloud St, Seattle, WA', '800-555-116', 'hello@freshdrop.com', 'Active', '2026-05-01', NULL);

-- ==========================================
-- 3. POPULATE PRODUCT TABLE (18 Rows)
-- IDs start at 1
-- ==========================================
INSERT INTO product (supplierID, product_name, product_type, inventory, price_each, size_ml, flavor, active) VALUES
(101, 'Alpine Crisp', 'Sparkling', 500, 3.00, 500, 'Lime', TRUE),
(101, 'Mountain Peak Mineral', 'Mineral', 250, 4.50, 750, 'Original', TRUE),
(102, 'Pacific Breeze', 'Sparkling', 0, 3.50, 500, 'Grapefruit', TRUE), 
(102, 'Pure Alkaline 9.5', 'Alkaline', 1000, 5.00, 1000, 'Original', TRUE),
(103, 'Glacier Freeze', 'Sparkling', 150, 4.00, 250, 'Berry', TRUE),
(103, 'Icelandic Nature', 'Mineral', 300, 6.00, 1500, 'Original', TRUE),
(104, 'Legacy Oasis', 'Alkaline', 0, 2.50, 500, 'Original', FALSE), 
(105, 'Fuji Essence', 'Alkaline', 800, 5.50, 500, 'Original', TRUE),
(106, 'Kentucky Limestone Water', 'Mineral', 400, 3.50, 1000, 'Original', TRUE),
(107, 'Ocean Fizz', 'Sparkling', 120, 3.00, 500, 'Mango', TRUE),
(108, 'Vibe Electro-Lite', 'Alkaline', 650, 4.00, 750, 'Lemon', TRUE),
(109, 'Cascade Splendor', 'Mineral', 200, 7.00, 2000, 'Original', TRUE),
(110, 'Zen Balance 8.0', 'Alkaline', 350, 4.50, 500, 'Original', TRUE),
(111, 'Arctic Frost', 'Sparkling', 80, 3.50, 500, 'Blackberry', TRUE),
(112, 'Deep Well Artesian', 'Mineral', 500, 3.00, 1500, 'Original', TRUE),
(113, 'Napa Gold Mineral', 'Mineral', 150, 8.00, 750, 'Original', TRUE),
(114, 'Old Stream Classic', 'Mineral', 0, 2.00, 500, 'Original', FALSE), 
(115, 'Fresh Splash', 'Sparkling', 900, 2.50, 250, 'Watermelon', TRUE);

-- ==========================================
-- 4. POPULATE SUBSCRIPTION TABLE (25 Rows)
-- IDs start at 100001 - Mapped explicitly for Box Sizes
-- ==========================================
INSERT INTO subscription (userID, plan_name, frequency, duration, box_size, status, start_date, end_date) VALUES
(10001, 'Mist', 'Weekly', 'Month', '4', 'Active', '2026-05-01', '2026-06-01'),
(10002, 'Dew', 'Bi Weekly', '6 Month', '8', 'Active', '2026-01-10', '2026-07-10'),
(10003, 'Drizzle', 'Monthly', 'Year', '16', 'Active', '2026-01-01', '2027-01-01'),
(10004, 'Downpour', 'Weekly', 'Year', '24', 'Active', '2026-03-15', '2027-03-15'),
(10005, 'Dew', 'Bi Weekly', '6 Month', '8', 'Inactive', '2025-06-01', '2025-12-01'), 
(10006, 'Mist', 'Weekly', 'Month', '4', 'Active', '2026-05-15', '2026-06-15'),
(10007, 'Drizzle', 'Bi Weekly', '6 Month', '16', 'Active', '2026-02-20', '2026-08-20'),
(10008, 'Downpour', 'Monthly', 'Year', '24', 'Active', '2026-01-05', '2027-01-05'),
(10009, 'Dew', 'Monthly', '6 Month', '8', 'Active', '2026-04-01', '2026-10-01'),
(10010, 'Mist', 'Weekly', 'Month', '4', 'Active', '2026-05-20', '2026-06-20'),
(10011, 'Drizzle', 'Weekly', 'Year', '16', 'Active', '2026-01-15', '2027-01-15'),
(10012, 'Downpour', 'Bi Weekly', '6 Month', '24', 'Active', '2026-03-01', '2026-09-01'),
(10013, 'Dew', 'Bi Weekly', '6 Month', '8', 'Active', '2026-02-14', '2026-08-14'),
(10014, 'Mist', 'Monthly', 'Month', '4', 'Inactive', '2025-10-01', '2025-11-01'), 
(10015, 'Downpour', 'Weekly', 'Year', '24', 'Active', '2026-05-01', '2027-05-01'),
(10016, 'Mist', 'Weekly', 'Month', '4', 'Active', '2026-05-02', '2026-06-02'),
(10017, 'Dew', 'Bi Weekly', '6 Month', '8', 'Active', '2026-03-10', '2026-09-10'),
(10018, 'Drizzle', 'Monthly', 'Year', '16', 'Active', '2026-02-01', '2027-02-01'),
(10019, 'Downpour', 'Weekly', 'Year', '24', 'Active', '2026-04-11', '2027-04-11'),
(10020, 'Dew', 'Bi Weekly', '6 Month', '8', 'Active', '2026-05-01', '2026-11-01'),
(10021, 'Mist', 'Weekly', 'Month', '4', 'Active', '2026-05-18', '2026-06-18'),
(10022, 'Drizzle', 'Monthly', 'Year', '16', 'Active', '2026-01-20', '2027-01-20'),
(10023, 'Downpour', 'Weekly', 'Year', '24', 'Active', '2026-03-01', '2027-03-01'),
(10024, 'Dew', 'Bi Weekly', '6 Month', '8', 'Active', '2026-02-28', '2026-08-28'),
(10025, 'Drizzle', 'Monthly', 'Year', '16', 'Active', '2026-05-10', '2027-05-10');

-- ==========================================
-- 5. POPULATE SPARKLING_WATER TABLE (6 Rows)
-- ==========================================
INSERT INTO sparkling_water (productID, carbonation_level) VALUES
(1, 'Medium'), (3, 'Heavy'), (5, 'Light'), (10, 'Medium'), (14, 'Heavy'), (18, 'Light');

-- ==========================================
-- 6. POPULATE MINERAL_WATER TABLE (7 Rows)
-- ==========================================
INSERT INTO mineral_water (productID, calcium_mg, magnesium_mg, sodium_mg, mineral_source) VALUES
(2, 45.20, 12.50, 5.00, 'Rocky Mountains'),
(6, 110.00, 40.25, 15.10, 'Icelandic Underground Aquifer'),
(9, 85.00, 30.00, 22.00, 'Kentucky Bluegrass Aquifer'),
(12, 12.00, 4.50, 1.20, 'Cascade Range Streams'),
(15, 0.00, 0.00, 0.00, 'Deep Well Pure Artesian'), 
(16, 200.50, 85.40, 45.00, 'Napa Hills Mineral Spring'),
(17, 35.00, 10.00, 8.00, 'Old Blue Ridge Spring'); 

-- ==========================================
-- 7. POPULATE ALKALINE_WATER TABLE (5 Rows)
-- ==========================================
INSERT INTO alkaline_water (productID, PH_Level) VALUES
(4, 9.5), (7, 7.0), (8, 8.8), (11, 9.0), (13, 8.0);

-- ==========================================
-- 8. POPULATE TRANSACTION TABLE (30 Rows)
-- IDs start at 6000001
-- Formula: total_cost = (price_each * quantity) * 1.10
-- Quantity matches the respective User's subscription box_size
-- ==========================================
INSERT INTO transaction (userID, productID, quantity, total_cost, receivedAt) VALUES
-- User 10001 (box_size 4) & Product 1 ($3.00) -> (3.00 * 4) * 1.10 = 13.20
(10001, 1, 4, 13.20, '2026-05-02'),
-- User 10002 (box_size 8) & Product 2 ($4.50) -> (4.50 * 8) * 1.10 = 39.60
(10002, 2, 8, 39.60, '2026-05-05'),
-- User 10003 (box_size 16) & Product 4 ($5.00) -> (5.00 * 16) * 1.10 = 88.00
(10003, 4, 16, 88.00, '2026-05-06'),
-- User 10004 (box_size 24) & Product 5 ($4.00) -> (4.00 * 24) * 1.10 = 105.60
(10004, 5, 24, 105.60, '2026-05-10'),
-- User 10006 (box_size 4) & Product 8 ($5.50) -> (5.50 * 4) * 1.10 = 24.20
(10006, 8, 4, 24.20, '2026-05-16'),
-- User 10007 (box_size 16) & Product 9 ($3.50) -> (3.50 * 16) * 1.10 = 61.60
(10007, 9, 16, 61.60, '2026-05-18'),
-- User 10008 (box_size 24) & Product 10 ($3.00) -> (3.00 * 24) * 1.10 = 79.20
(10008, 10, 24, 79.20, '2026-05-19'),
-- User 10009 (box_size 8) & Product 11 ($4.00) -> (4.00 * 8) * 1.10 = 35.20
(10009, 11, 8, 35.20, '2026-05-20'),
-- User 10010 (box_size 4) & Product 12 ($7.00) -> (7.00 * 4) * 1.10 = 30.80
(10010, 12, 4, 30.80, '2026-05-21'),
-- User 10011 (box_size 16) & Product 13 ($4.50) -> (4.50 * 16) * 1.10 = 79.20
(10011, 13, 16, 79.20, '2026-05-22'),
-- User 10012 (box_size 24) & Product 15 ($3.00) -> (3.00 * 24) * 1.10 = 79.20
(10012, 15, 24, 79.20, '2026-05-22'),
-- User 10013 (box_size 8) & Product 16 ($8.00) -> (8.00 * 8) * 1.10 = 70.40
(10013, 16, 8, 70.40, '2026-05-23'),
-- User 10015 (box_size 24) & Product 18 ($2.50) -> (2.50 * 24) * 1.10 = 66.00
(10015, 18, 24, 66.00, '2026-05-23'),
-- User 10016 (box_size 4) & Product 1 ($3.00) -> (3.00 * 4) * 1.10 = 13.20
(10016, 1, 4, 13.20, '2026-05-04'),
-- User 10017 (box_size 8) & Product 4 ($5.00) -> (5.00 * 8) * 1.10 = 44.00
(10017, 4, 8, 44.00, '2026-05-11'),
-- User 10018 (box_size 16) & Product 6 ($6.00) -> (6.00 * 16) * 1.10 = 105.60
(10018, 6, 16, 105.60, '2026-05-12'),
-- User 10019 (box_size 24) & Product 8 ($5.50) -> (5.50 * 24) * 1.10 = 145.20
(10019, 8, 24, 145.20, '2026-04-15'),
-- User 10020 (box_size 8) & Product 10 ($3.00) -> (3.00 * 8) * 1.10 = 26.40
(10020, 10, 8, 26.40, '2026-05-02'),
-- User 10021 (box_size 4) & Product 13 ($4.50) -> (4.50 * 4) * 1.10 = 19.80
(10021, 13, 4, 19.80, '2026-05-19'),
-- User 10022 (box_size 16) & Product 15 ($3.00) -> (3.00 * 16) * 1.10 = 52.80
(10022, 15, 16, 52.80, '2026-05-14'),
-- User 10023 (box_size 24) & Product 2 ($4.50) -> (4.50 * 24) * 1.10 = 118.80
(10023, 2, 24, 118.80, '2026-05-08'),
-- User 10024 (box_size 8) & Product 5 ($4.00) -> (4.00 * 8) * 1.10 = 35.20
(10024, 5, 8, 35.20, '2026-05-10'),
-- User 10025 (box_size 16) & Product 12 ($7.00) -> (7.00 * 16) * 1.10 = 123.20
(10025, 12, 16, 123.20, '2026-05-11'),
-- User 10001 (Second order - box_size 4) & Product 18 ($2.50) -> (2.50 * 4) * 1.10 = 11.00
(10001, 18, 4, 11.00, '2026-05-15'),
-- User 10002 (Second order - box_size 8) & Product 8 ($5.50) -> (5.50 * 8) * 1.10 = 48.40
(10002, 8, 8, 48.40, '2026-05-20'),
-- User 10006 (Second order - box_size 4) & Product 2 ($4.50) -> (4.50 * 4) * 1.10 = 19.80
(10006, 2, 4, 19.80, '2026-05-22'),
-- User 10017 (Second order - box_size 8) & Product 11 ($4.00) -> (4.00 * 8) * 1.10 = 35.20
(10017, 11, 8, 35.20, '2026-05-23'),
-- User 10020 (Second order - box_size 8) & Product 16 ($8.00) -> (8.00 * 8) * 1.10 = 70.40
(10020, 16, 8, 70.40, '2026-05-23'),
-- Edge Case: Past Inactive Subscriptions
(10005, 1, 8, 26.40, '2025-08-10'),
(10014, 6, 4, 26.40, '2025-10-15');

-- ==========================================
-- 9. POPULATE SHIPMENT TABLE (30 Rows)
-- IDs start at 1000001
-- ==========================================
INSERT INTO shipment (transactionID, status, schedule_date, shipment_date, tracking_number, address) VALUES
(6000001, 'Delivered', '2026-05-04', '2026-05-04', 'TRK-990001', '123 Water St, Seattle, WA'),
(6000002, 'Delivered', '2026-05-07', '2026-05-08', 'TRK-990002', '456 Rain Ave, Portland, OR'), 
(6000003, 'Delivered', '2026-05-08', '2026-05-08', 'TRK-990003', '789 Ocean Blvd, Miami, FL'),
(6000004, 'Out for Delivery', '2026-05-12', NULL, 'TRK-990004', '101 Puddle Ln, Austin, TX'),
(6000005, 'In Transit', '2026-05-18', NULL, 'TRK-990005', '303 River Dr, Boston, MA'),
(6000006, 'Label Created', '2026-05-20', NULL, 'TRK-990006', '404 Lake Way, Chicago, IL'),
(6000007, 'Received', '2026-05-22', NULL, 'TRK-990007', '505 Aqua Cir, Las Vegas, NV'),
(6000008, 'Received', '2026-05-23', NULL, 'TRK-990008', '606 Marine Dr, New York, NY'),
(6000009, 'Received', '2026-05-24', NULL, 'TRK-990009', '707 Creek Ct, Nashville, TN'),
(6000010, 'Received', '2026-05-25', NULL, 'TRK-990010', '808 Geyser Pl, San Diego, CA'),
(6000011, 'Received', '2026-05-25', NULL, 'TRK-990011', '909 Cascade Way, Phoenix, AZ'),
(6000012, 'Received', '2026-05-26', NULL, 'TRK-990012', '111 Glacier St, Salt Lake, UT'),
(6000013, 'Received', '2026-05-26', NULL, 'TRK-990013', '333 Mist Blvd, Scranton, PA'),
(6000014, 'Delivered', '2026-05-06', '2026-05-06', 'TRK-990014', '444 Clue Ave, River Heights, IL'),
(6000015, 'Delivered', '2026-05-13', '2026-05-13', 'TRK-990015', '555 Accounting Way, Scranton, PA'),
(6000016, 'Delivered', '2026-05-14', '2026-05-15', 'TRK-990016', '777 Art Lane, New York, NY'),
(6000017, 'Delivered', '2026-04-17', '2026-04-17', 'TRK-990017', '888 Lima Rd, Lima, OH'),
(6000018, 'Delivered', '2026-05-04', '2026-05-04', 'TRK-990018', '999 Queens Blvd, Queens, NY'),
(6000019, 'In Transit', '2026-05-21', NULL, 'TRK-990019', '123 Tech Noir St, Los Angeles, CA'),
(6000020, 'Label Created', '2026-05-16', NULL, 'TRK-990020', '456 Forest Ridge, Castaway, CA'),
(6000021, 'Delivered', '2026-05-10', '2026-05-10', 'TRK-990022', '789 Twin Towers, New York, NY'),
(6000022, 'Delivered', '2026-05-12', '2026-05-12', 'TRK-990022', '101 Modern Prometheus Rd, Geneva, CH'),
(6000023, 'Label Created', '2026-05-12', NULL, 'TRK-990023', '202 Neverland Way, London, UK'),
(6000024, 'In Transit', '2026-05-17', NULL, 'TRK-990024', '123 Water St, Seattle, WA'),
(6000025, 'Received', '2026-05-22', NULL, 'TRK-990025', '456 Rain Ave, Portland, OR'),
(6000026, 'Received', '2026-05-24', NULL, 'TRK-990026', '101 Puddle Ln, Austin, TX'),
(6000027, 'Received', '2026-05-25', NULL, 'TRK-990027', '555 Accounting Way, Scranton, PA'),
(6000028, 'Received', '2026-05-25', NULL, 'TRK-990028', '456 Forest Ridge, Castaway, CA'),
(6000029, 'Delivered', '2025-08-12', '2025-08-12', 'TRK-990029', '202 Stream Rd, Denver, CO'),
(6000030, 'Delivered', '2025-10-17', '2025-10-17', 'TRK-990030', '222 Fountain Ave, San Francisco, CA');

-- ==========================================
-- 10. POPULATE PRODUCT_REVIEW TABLE (30 Rows)
-- ==========================================
INSERT INTO product_review (reviewID, userID, transactionID, rating, review_comment, review_date) VALUES
('REV-2026-001', 10001, 6000001, 5, 'Exceptional crisp taste. Lime flavor is perfectly natural.', '2026-05-05'),
('REV-2026-002', 10002, 6000002, 4, 'Great mineral profile, but bottle cap was a little tight.', '2026-05-09'),
('REV-2026-003', 10003, 6000003, 5, 'Highly recommend the 9.5 pH Alkaline water. Feel super hydrated.', '2026-05-10'),
('REV-2026-004', 10004, 6000004, 3, 'The berry sparkling flavor is muted, but carbonation level is fantastic.', '2026-05-14'),
('REV-2026-005', 10006, 6000005, 5, 'Fuji water never misses. Will keep this subscription tier.', '2026-05-19'),
('REV-2026-006', 10007, 6000006, 2, 'A bit too heavy on the sodium side for my dynamic tastes.', '2026-05-20'),
('REV-2026-007', 10008, 6000007, 4, 'Awesome mango flavoring!', '2026-05-21'),
('REV-2026-008', 10009, 6000008, 5, 'Clean taste, prompt processing.', '2026-05-22'),
('REV-2026-009', 10010, 6000009, 1, 'Arrived warm, and the box was completely beat up.', '2026-05-23'),
('REV-2026-010', 10011, 6000010, 4, 'Solid alkaline water structure.', '2026-05-23'),
('REV-2026-011', 10012, 6000011, 5, 'Deep well waters are clean and clear.', '2026-05-23'),
('REV-2026-012', 10013, 6000012, 3, 'Extremely premium mineral water, but way too expensive.', '2026-05-23'),
('REV-2026-013', 10015, 6000013, 5, 'Watermelon sparkler is a summer essential!', '2026-05-23'),
('REV-2026-014', 10016, 6000014, 4, 'Classic sparkling water, hits the spot every time.', '2026-05-07'),
('REV-2026-015', 10017, 6000015, 5, 'My skin feels incredible after drinking alkaline for a week.', '2026-05-15'),
('REV-2026-016', 10018, 6000016, 4, 'High quality mineral water, pristine extraction.', '2026-05-17'),
('REV-2026-017', 10019, 6000017, 5, 'The best hydration option available in bulk format.', '2026-04-20'),
('REV-2026-018', 10020, 6000018, 3, 'Average sparkling water. Nothing wild or mindblowing.', '2026-05-06'),
('REV-2026-019', 10021, 6000019, 4, 'Very well-balanced flavor footprint.', '2026-05-22'),
('REV-2026-020', 10022, 6000020, 5, 'The absolute standard for pure arthesian springs.', '2026-05-18'),
('REV-2026-021', 10023, 6000021, 4, 'Clean, simple, mineral refreshment.', '2026-05-12'),
('REV-2026-022', 10024, 6000022, 3, 'The carbonation dies quick once opened, drink up quickly!', '2026-05-13'),
('REV-2026-023', 10025, 6000023, 5, 'Top tier value for a luxury cascade brand.', '2026-05-14'),
('REV-2026-024', 10001, 6000024, 4, 'Watermelon addition is fantastic for workouts.', '2026-05-17'),
('REV-2026-025', 10002, 6000025, 5, 'Alkaline balance profile remains undefeated.', '2026-05-22'),
('REV-2026-026', 10006, 6000026, 4, 'Very good mineral option.', '2026-05-23'),
('REV-2026-027', 10017, 6000027, 4, 'Great backup supply setup.', '2026-05-23'),
('REV-2026-028', 10020, 6000028, 5, 'Unbelievable premium processing.', '2026-05-23'),
('REV-2025-054', 10005, 6000029, 4, 'Great bulk packaging options.', '2025-08-15'),
('REV-2025-099', 10014, 6000030, 5, 'Sad that this supplier went offline, this water was legendary.', '2025-10-20');
